<?php

/**
 * @file
 * Contains spin_settings.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string
 */
function spectrum_settings_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    // Main module help for the spin_settings module.
    case 'help.page.spectrum_settings':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Spectrum settings module') . '</p>';

    default:
  }

  return $output;
}

/**
 * Implements hook_preprocess_html().
 *
 * @param array $vars
 */
function spin_settings_preprocess_html(&$vars) {
  // Allow Google Analytics account to be available for the theme layer.
  $vars['ga_account'] = \Drupal::state()->get('ga_account');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function spectrum_settings_preprocess_page(&$variables) {
  /** @var \Drupal\Core\Theme\ActiveTheme $activeTheme */
  $activeTheme = \Drupal::service('theme.manager')->getActiveTheme();
  // Remove the prerender content if the is seven.
  if ($activeTheme->getName() == 'seven') {
    unset($variables['page']['content']['prerendered']);
    return;
  }

  /** @var \Drupal\node\NodeInterface $node */
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {
    /** @var \Drupal\prerender\PrerenderServiceInterface $prerender_service */
    $prerender_service = \Drupal::service('prerender.prerender');

    // Get the renderer.
    /** @var \Drupal\Core\Render\RendererInterface $renderer */
    $renderer = \Drupal::service('renderer');

    /** @var \Drupal\prerender\Entity\PrerenderedDataInterface $prerendered_data */
    $prerendered_data = $prerender_service->getData($node->toUrl()->toString());
    if ($prerendered_data && $prerendered_data->id()) {
      $variables['page']['content']['prerendered'] = $prerendered_data->getRenderArray($renderer);
    }
  }
}

/**
 * Implements hook_entity_update().
 */
function spectrum_settings_node_update(\Drupal\node\NodeInterface $node) {
  \Drupal::service('pathauto.generator')->updateEntityAlias($node, 'update');
  /** @var \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager */
  $entityTypeManager = \Drupal::service('entity_type.manager');
  /** @var \Drupal\prerender\PrerenderService $prerenderService */
  $prerenderService = \Drupal::service('prerender.prerender');

  // Get node url.
  $url = $node->toUrl();
  $requestedPath = $url->toString();

  // Load prerender entity and update to the queue.
  $prerenderedDatas = $entityTypeManager->getStorage('prerendered_html_entity')
    ->loadByProperties([
      'target_uuid' => $node->uuid(),
      'entity_type' => $node->getEntityType()->id(),
    ]);
  foreach ($prerenderedDatas as $prerenderedData) {
    /** @var \Drupal\prerender\Entity\PrerenderedDataInterface $prerenderedData */
    $prerenderedData->setRequestPath($requestedPath);
    $prerenderedData->save();
    $prerenderService->queueData($prerenderedData, TRUE);
  }
}

/**
 * Implements hook_query_TAG_alter() for entity reference selection handlers.
 *
 * We like tho show always 30 results instead of the 10 definied in EntityAutocompleteMatcher::getMatches()
 */
function spectrum_settings_query_entity_reference_alter(AlterableInterface $query) {
  $query->range(0, 30);
}

/**
 * Implements hook_form_alter().
 */
function spectrum_settings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['#entity_type']) && $form['#entity_type'] == 'media') {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'spectrum_settings_media_form_submit';
      }
    }
  }
}

/**
 * Redirect to the media admin page after save media entity.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function spectrum_settings_media_form_submit($form, FormStateInterface $form_state) {
  $media = $form_state->getFormObject()->getEntity();
  if ($media->id()) {
    if ($media->access('edit')) {
      $url = Url::fromRoute('view.media.media_page_list');
      $form_state->setRedirectUrl($url);
    }
    else {
      $form_state->setRedirect('<front>');
    }
  }
}
