<?php

/**
 * @file
 * Contains spin_settings.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string
 */
function spectrum_settings_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    // Main module help for the spin_settings module.
    case 'help.page.spectrum_settings':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Spectrum settings module') . '</p>';

    default:
  }

  return $output;
}

/**
 * Implements hook_preprocess_html().
 *
 * @param array $vars
 */
function spin_settings_preprocess_html(&$vars) {
  // Allow Google Analytics account to be available for the theme layer.
  $vars['ga_account'] = \Drupal::state()->get('ga_account');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function spectrum_settings_preprocess_page(&$variables) {
  /** @var \Drupal\Core\Theme\ActiveTheme $activeTheme */
  $activeTheme = \Drupal::service('theme.manager')->getActiveTheme();
  // Remove the prerender content if the is seven.
  if ($activeTheme->getName() == 'seven') {
    unset($variables['page']['content']['prerendered']);
    return;
  }

  /** @var \Drupal\node\NodeInterface $node */
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {
    /** @var \Drupal\prerender\PrerenderServiceInterface $prerender_service */
    $prerender_service = \Drupal::service('prerender.prerender');

    // Get the renderer.
    /** @var \Drupal\Core\Render\RendererInterface $renderer */
    $renderer = \Drupal::service('renderer');

    /** @var \Drupal\prerender\Entity\PrerenderedDataInterface $prerendered_data */
    $prerendered_data = $prerender_service->getData($node->toUrl()->toString());
    if ($prerendered_data && $prerendered_data->id()) {
      $variables['page']['content']['prerendered'] = $prerendered_data->getRenderArray($renderer);
    }
  }
}
