<?php

/**
 * @file
 * Contains spin_settings.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string
 */
function spectrum_settings_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    // Main module help for the spin_settings module.
    case 'help.page.spectrum_settings':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Spectrum settings module') . '</p>';

    default:
  }

  return $output;
}

/**
 * Implements hook_preprocess_html().
 *
 * @param array $vars
 */
function spin_settings_preprocess_html(&$vars) {
  // Allow Google Analytics account to be available for the theme layer.
  $vars['ga_account'] = \Drupal::state()->get('ga_account');
}
