import DefaultSlideoutPanelTransitionController from "../DefaultSlideoutPanelTransitionController";

class GlobalSlideoutPanelTransitionController extends DefaultSlideoutPanelTransitionController
{


}

export default GlobalSlideoutPanelTransitionController;
