<?php

/**
 * @file
 * Contains spectrum_alter_autocomplete.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function spectrum_alter_autocomplete_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spectrum_alter_autocomplete module.
    case 'help.page.spectrum_alter_autocomplete':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Spectrum alter autocomplete') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_input().
 * Applied for entity_autocomplete field.
 */
function spectrum_alter_autocomplete_preprocess_input(&$variables) {
  if ($variables["element"]["#type"] == 'entity_autocomplete') {
    $variables["#attached"]["library"][] = 'spectrum_alter_autocomplete/spectrum_alter_autocomplete.autocomplete_box';
  }
}
