enum MapTertiarySlideType
{
	RADIAL_PROGRESS = 0,
	VERTICAL_GRAPHIC = 1,
	HORIZONTAL_WITH_ICON = 2,
	HORIZONTAL_WITHOUT_ICON = 3,
	ICON_PROGRESS = 4,
	VERTICAL_LIST = 5,
	CARDS = 6
}

export default MapTertiarySlideType;